spring.application.name=suko-shop
spring.datasource.url=jdbc:h2:mem:shop;DB_CLOSE_DELAY=-1
spring.sql.init.mode=always
spring.h2.console.enabled=false
gg.jte.development-mode=true
gg.jte.template-location=src/main/jte
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.same-site=lax
