@param String id
@param String name
@param String type = "text"
@param boolean required = false
@param String placeholder = null

<input id="${id}" name="${name}" type="${type}" required="${required}" placeholder="${placeholder}" class="${"block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-blue-600 sm:text-sm sm:leading-6"}"/>